import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";

const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Envision - Talent Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
